AllCops:
  Exclude:
    - '**/schema.rb'
    - 'vendor/**/*'
    - 'db/migrate/*'
  TargetRubyVersion: 2.2

Rails:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Style/MultilineBlockChain:
  Enabled: false
