base: &defaults
  adapter: mysql2
  database: <%= ENV['DB_DATABASE_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  host: <%= ENV['DB_HOST'] %>
  encoding: utf8
  reconnect: true
  pool: 30

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults
  password: <%= ENV['DB_PASSWORD'] %>
